CREATE TABLE "mytable" (
  "------------------Zapytania-------------------" text
);

INSERT INTO "mytable" ("------------------Zapytania-------------------")
VALUES
('------------------1-------------------'),
('WITH base AS ('),
('SELECT'),
('be.booking_id'),
('be.bow_id'),
('be.be_quantity'),
('e.b_model'),
('e.b_weight'),
('e.b_length'),
('s.s_starts_at'),
('b.requested_at'),
('COALESCE(s.s_starts_at'),
('FROM archery.booking_equipment be'),
('JOIN archery.equipment e      ON e.bow_id = be.bow_id'),
('JOIN archery.bookings b       ON b.booking_id = be.booking_id'),
('LEFT JOIN archery.sessions s  ON s.session_id = b.session_id'),
(')'),
('num_feats AS ('),
('SELECT'),
('booking_id'),
('bow_id'),
('be_quantity'),
('b_model'),
('b_weight AS weight_lbs'),
('b_length AS length_in'),
('event_ts'),
('FROM base'),
(')'),
('scores AS ('),
('SELECT'),
('e.bow_id'),
('e.b_model'),
('SUM(be.be_quantity)           AS total_quantity'),
('COUNT(DISTINCT be.booking_id) AS bookings_count'),
('FROM archery.booking_equipment be'),
('JOIN archery.equipment e ON e.bow_id = be.bow_id'),
('GROUP BY e.bow_id'),
(')'),
('recency AS ('),
('-- half-life ~14 dni (lambda ≈ ln(2)/14 ≈ 0.0495/dzień)'),
('SELECT'),
('bow_id'),
('SUM(be_quantity * exp( -0.0495 * EXTRACT(EPOCH FROM (now() - event_ts)) / 86400.0 )) AS recent_score'),
('FROM num_feats'),
('GROUP BY bow_id'),
(')'),
('SELECT'),
('e.bow_id'),
('e.b_model'),
('NULLIF(regexp_replace(e.b_weight'),
('NULLIF(regexp_replace(e.b_length'),
('s.total_quantity'),
('s.bookings_count'),
('r.recent_score'),
('FROM archery.equipment e'),
('LEFT JOIN scores  s ON s.bow_id = e.bow_id'),
('LEFT JOIN recency r ON r.bow_id = e.bow_id'),
('ORDER BY COALESCE(r.recent_score'),
('LIMIT 15;'),
('------------------2-------------------'),
('WITH paid AS ('),
('SELECT p.payment_id'),
('FROM archery.payments p'),
('WHERE p.status_id = (SELECT status_id FROM archery.payment_statuses WHERE name = ''paid'')'),
('AND p.p_date >= now()'),
(')'),
('joined AS ('),
('SELECT'),
('tf.field_id'),
('tf.f_name'),
('date_trunc(''day'''),
('p.p_amount'),
('FROM paid p'),
('JOIN archery.bookings b ON b.booking_id = p.booking_id'),
('JOIN archery.sessions s ON s.session_id = b.session_id'),
('JOIN archery.training_fields tf ON tf.field_id = s.field_id'),
(')'),
('SELECT'),
('j.field_id'),
('j.f_name AS field_name'),
('j.day'),
('COUNT(*)        AS payments_count'),
('SUM(j.p_amount) AS revenue_total'),
('AVG(j.p_amount) AS revenue_avg'),
('FROM joined j'),
('GROUP BY j.field_id'),
('ORDER BY j.day DESC');
