CREATE TABLE "mytable" (
  "------------------Widoki-------------------" text
);

INSERT INTO "mytable" ("------------------Widoki-------------------")
VALUES
('------------------1-------------------'),
('CREATE OR REPLACE VIEW archery.v_trainer_workload_next_30d AS'),
('SELECT'),
('t.trainer_id'),
('COALESCE(cm.m_name || '' '' || cm.m_surname'),
('COUNT(s.session_id)                                                  AS sessions_count'),
('COALESCE(SUM(s.s_duration_minutes)'),
('MIN(s.s_starts_at)                                                   AS first_session'),
('MAX(s.s_starts_at)                                                   AS last_session'),
('COUNT(*) FILTER (WHERE st.st_role = ''lead'')                          AS lead_sessions'),
('COUNT(*) FILTER (WHERE st.st_role = ''assistant'')                     AS assistant_sessions'),
('FROM archery.trainers t'),
('LEFT JOIN archery.sessions_trainers st ON st.trainer_id = t.trainer_id'),
('LEFT JOIN archery.sessions s'),
('ON s.session_id = st.session_id'),
('AND s.s_starts_at >= now()'),
('AND s.s_starts_at <  now() + interval ''30 days'''),
('LEFT JOIN archery.club_members cm ON cm.member_id = t.member_id'),
('GROUP BY t.trainer_id'),
('ORDER BY sessions_count DESC'),
('GRANT SELECT ON archery.v_trainer_workload_next_30d TO app_staff;'),
('--select * from archery.v_trainer_workload_next_30d'),
('------------------2-------------------'),
('CREATE OR REPLACE VIEW archery.v_field_utilization_monthly AS'),
('SELECT'),
('tf.field_id'),
('tf.f_name AS field_name'),
('date_trunc(''month'''),
('COUNT(*)                                   AS sessions_count'),
('SUM(s.s_duration_minutes)                  AS scheduled_minutes'),
('FROM archery.sessions s'),
('JOIN archery.training_fields tf ON tf.field_id = s.field_id'),
('GROUP BY tf.field_id'),
('ORDER BY month DESC'),
('GRANT SELECT ON archery.v_field_utilization_monthly TO app_member'),
('--select * from archery.v_field_utilization_monthly'),
('------------------3-------------------'),
('CREATE OR REPLACE VIEW archery.v_member_scores AS'),
('SELECT'),
('cm.member_id'),
('cm.m_name || '' '' || cm.m_surname AS member_name'),
('s.sc_points'),
('FROM archery.scores s'),
('JOIN archery.club_members cm ON cm.member_id = s.member_id'),
('ORDER BY s.sc_points DESC;'),
('GRANT SELECT ON archery.v_member_scores TO app_member;'),
('--select * from archery.v_member_scores'),
('------------------4-------------------'),
('CREATE OR REPLACE VIEW archery.v_sessions_basic AS'),
('SELECT'),
('s.session_id'),
('tf.f_name          AS field_name'),
('s.s_starts_at'),
('s.s_duration_minutes'),
('s.s_max_number_of_participants'),
('FROM archery.sessions s'),
('JOIN archery.training_fields tf ON tf.field_id = s.field_id'),
('ORDER BY s.s_starts_at;'),
('GRANT SELECT ON archery.v_sessions_basic TO app_member;'),
('--select * from archery.v_sessions_basic'),
('------------------5-------------------'),
('CREATE OR REPLACE VIEW archery.v_training_fields_overview AS'),
('SELECT'),
('tf.field_id'),
('tf.f_name            AS field_name'),
('tf.f_difficulty_level'),
('tf.f_capacity'),
('CASE WHEN tf.f_is_outdoors THEN ''outdoor'' ELSE ''indoor'' END AS location_type'),
('FROM archery.training_fields tf'),
('ORDER BY tf.field_id;'),
('GRANT SELECT ON archery.v_training_fields_overview TO app_member;'),
('--select * from archery.v_training_fields_overview'),
('------------------6-------------------'),
('CREATE OR REPLACE VIEW archery.v_dictionaries AS'),
('SELECT ''reservation_status'' AS dict'),
('FROM archery.reservation_statuses rs'),
('UNION ALL'),
('SELECT ''payment_method'''),
('UNION ALL'),
('SELECT ''payment_status'''),
('UNION ALL'),
('SELECT ''currency'''),
('GRANT SELECT ON archery.v_dictionaries TO app_member;'),
('--select * from archery.v_dictionaries'),
('------------------7-------------------'),
('CREATE OR REPLACE VIEW archery.v_equipment_catalog AS'),
('SELECT'),
('e.bow_id'),
('e.b_model'),
('e.b_weight'),
('e.b_length'),
('FROM archery.equipment e;'),
('GRANT SELECT ON archery.v_equipment_catalog TO app_member;'),
('--select * from archery.v_equipment_catalog'),
('------------------8-------------------'),
('CREATE OR REPLACE VIEW archery.v_bow_popularity AS'),
('SELECT e.bow_id'),
('FROM archery.equipment e'),
('JOIN archery.booking_equipment be USING (bow_id)'),
('GROUP BY e.bow_id'),
('ORDER BY total_quantity DESC;'),
('GRANT SELECT ON archery.v_bow_popularity TO app_member;'),
('--select * from archery.v_bow_popularity'),
('------------------Usunięcie dostępów poza widokami-------------------'),
('REVOKE SELECT ON'),
('archery.training_fields'),
('archery.sessions'),
('archery.equipment'),
('archery.reservation_statuses'),
('archery.payment_methods'),
('archery.payment_statuses'),
('archery.currencies'),
('archery.scores'),
('FROM app_member;');
