CREATE TABLE "mytable" (
  "------------------t1-------------------" text
);

INSERT INTO "mytable" ("------------------t1-------------------")
VALUES
('--sukces check'),
('SET ROLE member_demo;'),
('SELECT field_id'),
('SELECT session_id'),
('RESET ROLE;'),
('------------------t2-------------------'),
('--sukces check'),
('SET ROLE member_demo;'),
('INSERT INTO archery.bookings(member_id'),
('SELECT'),
('(SELECT member_id FROM archery.v_member_ids ORDER BY random() LIMIT 1)'),
('(SELECT status_id FROM archery.reservation_statuses WHERE name=''pending'')'),
('now();'),
('RESET ROLE;'),
('------------------t3-------------------'),
('--sukces check'),
('SET ROLE member_demo;'),
('INSERT INTO archery.booking_equipment(booking_id'),
('SELECT b.booking_id'),
('FROM archery.bookings b'),
('JOIN archery.equipment e ON TRUE'),
('ORDER BY b.booking_id DESC'),
('LIMIT 1;'),
('RESET ROLE;'),
('------------------t4-------------------'),
('--fail check'),
('SET ROLE member_demo;'),
('SELECT * FROM archery.payments LIMIT 1;'),
('RESET ROLE;'),
('------------------t5-------------------'),
('--fail check'),
('SET ROLE member_demo;'),
('UPDATE archery.sessions'),
('SET s_max_number_of_participants = 99'),
('WHERE session_id = (SELECT session_id FROM archery.sessions LIMIT 1);'),
('RESET ROLE;'),
('------------------t6-------------------'),
('--fail check'),
('SET ROLE member_demo;'),
('SELECT session_id'),
('UPDATE archery.sessions'),
('SET s_max_number_of_participants = s_max_number_of_participants'),
('WHERE false;'),
('RESET ROLE;'),
('------------------t7-------------------'),
('--fail check'),
('SET ROLE member_demo;'),
('SELECT trainer_id FROM trainers LIMIT 3;'),
('RESET ROLE;');
