CREATE TABLE "mytable" (
  "------------------Role-------------------" text
);

INSERT INTO "mytable" ("------------------Role-------------------")
VALUES
('CREATE ROLE app_member NOINHERIT;'),
('CREATE ROLE app_staff  NOINHERIT;'),
('CREATE USER member_demo LOGIN PASSWORD ''xxx'';'),
('CREATE USER staff_demo  LOGIN PASSWORD ''xxx'';'),
('GRANT app_member TO member_demo;'),
('GRANT app_staff  TO staff_demo;'),
('REVOKE ALL ON SCHEMA archery FROM PUBLIC;'),
('GRANT USAGE ON SCHEMA archery TO app_member'),
('------------------Dostępy klienta-------------------'),
('GRANT SELECT ON'),
('archery.training_fields'),
('archery.scores'),
('archery.sessions'),
('archery.equipment'),
('archery.reservation_statuses'),
('archery.payment_methods'),
('archery.payment_statuses'),
('archery.currencies'),
('TO app_member;'),
('GRANT SELECT'),
('archery.bookings'),
('archery.booking_equipment'),
('TO app_member;'),
('GRANT SELECT'),
('archery.club_members'),
('archery.trainers'),
('archery.training_fields'),
('archery.sessions'),
('archery.sessions_trainers'),
('archery.bookings'),
('archery.booking_equipment'),
('archery.equipment'),
('archery.payments'),
('archery.scores'),
('TO app_staff;'),
('GRANT SELECT ON'),
('archery.reservation_statuses'),
('archery.payment_methods'),
('archery.payment_statuses'),
('archery.currencies'),
('TO app_staff;');
