CREATE TABLE "mytable" (
  "CREATE OR ALTER PROCEDURE dbo.sp_add_member" text
);

INSERT INTO "mytable" ("CREATE OR ALTER PROCEDURE dbo.sp_add_member")
VALUES
('@p_name          NVARCHAR(100)'),
('@p_surname       NVARCHAR(100)'),
('@p_email         NVARCHAR(255) = NULL'),
('@p_phone_number  NVARCHAR(50)  = NULL'),
('AS'),
('BEGIN'),
('SET NOCOUNT ON;'),
('DECLARE @v_member_id BIGINT;'),
('DECLARE @v_exists    BIT;'),
('IF @p_phone_number IS NOT NULL'),
('BEGIN'),
('SELECT @v_exists = CASE WHEN EXISTS ('),
('SELECT 1'),
('FROM dbo.club_members'),
('WHERE m_phone_number = @p_phone_number'),
(') THEN 1 ELSE 0 END;'),
('IF @v_exists = 1'),
('BEGIN'),
('RAISERROR(''Phone number %s is already used'''),
('RETURN;'),
('END'),
('END'),
('IF @p_email IS NOT NULL'),
('BEGIN'),
('SELECT @v_exists = CASE WHEN EXISTS ('),
('SELECT 1'),
('FROM dbo.club_members'),
('WHERE m_email = @p_email'),
(') THEN 1 ELSE 0 END;'),
('IF @v_exists = 1'),
('BEGIN'),
('RAISERROR(''Email %s is already used'''),
('RETURN;'),
('END'),
('END'),
('INSERT INTO dbo.club_members (m_name'),
('VALUES (@p_name'),
('SET @v_member_id = SCOPE_IDENTITY();'),
('INSERT INTO dbo.scores (member_id'),
('VALUES (@v_member_id'),
('END;'),
('GO'),
('CREATE TYPE dbo.BookingEquipmentItem AS TABLE'),
('('),
('bow_id   BIGINT NOT NULL'),
('quantity INT    NOT NULL'),
(');'),
('GO'),
('CREATE OR ALTER PROCEDURE dbo.sp_create_booking_with_equipment'),
('@p_member_id BIGINT'),
('@p_session_id BIGINT'),
('@items dbo.BookingEquipmentItem READONLY'),
('AS'),
('BEGIN'),
('SET NOCOUNT ON;'),
('DECLARE'),
('@v_booking_id        BIGINT'),
('@v_status_pending_id INT'),
('@v_member_exists     BIT'),
('@v_session_exists    BIT'),
('@v_current_bookings  INT'),
('@v_max_participants  INT'),
('@v_bow_exists        BIT;'),
('BEGIN TRY'),
('BEGIN TRAN;'),
('SELECT @v_member_exists = CASE WHEN EXISTS ('),
('SELECT 1 FROM dbo.club_members WHERE member_id = @p_member_id'),
(') THEN 1 ELSE 0 END;'),
('IF @v_member_exists = 0'),
('BEGIN'),
('RAISERROR(''Member %d does not exist'''),
('ROLLBACK TRAN;'),
('RETURN;'),
('END'),
('SELECT @v_session_exists = CASE WHEN EXISTS ('),
('SELECT 1 FROM dbo.sessions WHERE session_id = @p_session_id'),
(') THEN 1 ELSE 0 END;'),
('IF @v_session_exists = 0'),
('BEGIN'),
('RAISERROR(''Session %d does not exist'''),
('ROLLBACK TRAN;'),
('RETURN;'),
('END'),
('SELECT @v_max_participants = s_max_number_of_participants'),
('FROM dbo.sessions'),
('WHERE session_id = @p_session_id;'),
('SELECT @v_current_bookings = COUNT(*)'),
('FROM dbo.bookings'),
('WHERE session_id = @p_session_id;'),
('IF @v_current_bookings >= @v_max_participants'),
('BEGIN'),
('RAISERROR(''Session is full – cannot add more bookings.'''),
('RETURN;'),
('END;'),
('SELECT @v_status_pending_id = status_id'),
('FROM dbo.reservation_statuses'),
('WHERE name = ''pending'';'),
('IF @v_status_pending_id IS NULL'),
('BEGIN'),
('RAISERROR(''Reservation status "pending" not found'''),
('ROLLBACK TRAN;'),
('RETURN;'),
('END'),
('INSERT INTO dbo.bookings ('),
('member_id'),
('reservation_status_id'),
(')'),
('VALUES ('),
('@p_member_id'),
('@v_status_pending_id'),
(');'),
('SET @v_booking_id = SCOPE_IDENTITY();'),
('DECLARE cur CURSOR LOCAL FAST_FORWARD FOR'),
('SELECT bow_id'),
('FROM @items;'),
('DECLARE @v_bow_id BIGINT;'),
('DECLARE @v_qty    INT;'),
('OPEN cur;'),
('FETCH NEXT FROM cur INTO @v_bow_id'),
('WHILE @@FETCH_STATUS = 0'),
('BEGIN'),
('IF @v_qty IS NULL OR @v_qty <= 0'),
('BEGIN'),
('RAISERROR(''Quantity for bow_id %d must be positive'''),
('ROLLBACK TRAN;'),
('CLOSE cur;'),
('DEALLOCATE cur;'),
('RETURN;'),
('END'),
('SELECT @v_bow_exists = CASE WHEN EXISTS ('),
('SELECT 1 FROM dbo.equipment WHERE bow_id = @v_bow_id'),
(') THEN 1 ELSE 0 END;'),
('IF @v_bow_exists = 0'),
('BEGIN'),
('RAISERROR(''Bow_id %d not found in equipment'''),
('ROLLBACK TRAN;'),
('CLOSE cur;'),
('DEALLOCATE cur;'),
('RETURN;'),
('END'),
('INSERT INTO dbo.booking_equipment (booking_id'),
('VALUES (@v_booking_id'),
('FETCH NEXT FROM cur INTO @v_bow_id'),
('END'),
('CLOSE cur;'),
('DEALLOCATE cur;'),
('COMMIT TRAN;'),
('END TRY'),
('BEGIN CATCH'),
('IF @@TRANCOUNT > 0'),
('ROLLBACK TRAN;'),
('THROW;'),
('END CATCH'),
('END;'),
('GO'),
('CREATE OR ALTER FUNCTION dbo.fn_member_discount'),
('('),
('@member_id BIGINT'),
(')'),
('RETURNS DECIMAL(5'),
('AS'),
('BEGIN'),
('DECLARE @v_points   DECIMAL(10'),
('DECLARE @v_discount DECIMAL(5'),
('SELECT @v_points = sc_points'),
('FROM dbo.scores'),
('WHERE member_id = @member_id;'),
('IF @v_points IS NULL'),
('SET @v_points = 0;'),
('IF @v_points < 100'),
('SET @v_discount = 0;'),
('ELSE IF @v_points < 200'),
('SET @v_discount = 5;'),
('ELSE IF @v_points < 500'),
('SET @v_discount = 10;'),
('ELSE'),
('SET @v_discount = 15;'),
('RETURN @v_discount;'),
('END;'),
('GO');
