CREATE TABLE "mytable" (
  "USE master;" text NULL
);

INSERT INTO "mytable" ("USE master;")
VALUES
('GO'),
('ALTER DATABASE postgres_mirror'),
('SET SINGLE_USER WITH ROLLBACK IMMEDIATE;'),
('GO'),
('DROP DATABASE postgres_mirror;'),
('GO'),
('CREATE DATABASE postgres_mirror;'),
('GO'),
('USE postgres_mirror'),
('GO'),
('CREATE TABLE dbo.club_members ('),
('member_id       BIGINT IDENTITY(1'),
('m_name          NVARCHAR(100) NOT NULL'),
('m_surname       NVARCHAR(100) NOT NULL'),
('m_email         NVARCHAR(255) NULL'),
('m_phone_number  NVARCHAR(50)  NOT NULL'),
('m_last_active   DATETIME2(0)  NOT NULL CONSTRAINT df_club_members_last_active DEFAULT SYSDATETIME()'),
(NULL),
('CONSTRAINT pk_club_members PRIMARY KEY (member_id)'),
('CONSTRAINT uq_club_members_email         UNIQUE (m_email)'),
('CONSTRAINT uq_club_members_phone_number  UNIQUE (m_phone_number)'),
(');'),
('GO'),
('ALTER TABLE dbo.club_members'),
('DROP CONSTRAINT uq_club_members_email;'),
('CREATE UNIQUE INDEX uq_club_members_email'),
('ON dbo.club_members (m_email)'),
('WHERE m_email IS NOT NULL;'),
('CREATE TABLE dbo.currencies ('),
('currency_id SMALLINT IDENTITY(1'),
('code        NCHAR(3)               NOT NULL'),
(NULL),
('CONSTRAINT pk_currencies       PRIMARY KEY (currency_id)'),
('CONSTRAINT uq_currencies_code  UNIQUE (code)'),
(');'),
('GO'),
('CREATE TABLE dbo.daily_field_revenue ('),
('r_date               DATE          NOT NULL'),
('field_id             INT           NOT NULL'),
('field_name           NVARCHAR(255) NOT NULL'),
('paid_bookings_count  INT           NOT NULL'),
('total_revenue        DECIMAL(12'),
(NULL),
('CONSTRAINT pk_daily_field_revenue PRIMARY KEY (r_date'),
(');'),
('GO'),
('CREATE TABLE dbo.equipment ('),
('bow_id    BIGINT IDENTITY(1'),
('b_model   NVARCHAR(100)        NOT NULL'),
('b_weight  NVARCHAR(50)         NOT NULL'),
('b_length  NVARCHAR(50)         NOT NULL'),
(NULL),
('CONSTRAINT pk_equipment PRIMARY KEY (bow_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.payment_methods ('),
('method_id SMALLINT IDENTITY(1'),
('name      NVARCHAR(100)          NOT NULL'),
(NULL),
('CONSTRAINT pk_payment_methods       PRIMARY KEY (method_id)'),
('CONSTRAINT uq_payment_methods_name  UNIQUE (name)'),
(');'),
('GO'),
('CREATE TABLE dbo.payment_statuses ('),
('status_id SMALLINT IDENTITY(1'),
('name      NVARCHAR(100)          NOT NULL'),
(NULL),
('CONSTRAINT pk_payment_statuses       PRIMARY KEY (status_id)'),
('CONSTRAINT uq_payment_statuses_name  UNIQUE (name)'),
(');'),
('GO'),
('CREATE TABLE dbo.reservation_statuses ('),
('status_id SMALLINT IDENTITY(1'),
('name      NVARCHAR(100)          NOT NULL'),
(NULL),
('CONSTRAINT pk_reservation_statuses       PRIMARY KEY (status_id)'),
('CONSTRAINT uq_reservation_statuses_name  UNIQUE (name)'),
(');'),
('GO'),
('CREATE TABLE dbo.training_fields ('),
('field_id            BIGINT IDENTITY(1'),
('f_difficulty_level  INT                  NOT NULL'),
('f_is_outdoors       BIT                  NOT NULL'),
('f_name              NVARCHAR(100)        NOT NULL'),
('f_capacity          INT                  NOT NULL'),
(NULL),
('CONSTRAINT pk_training_fields PRIMARY KEY (field_id)'),
('CONSTRAINT ck_training_fields_capacity'),
('CHECK (f_capacity >= 1)'),
('CONSTRAINT ck_training_fields_difficulty'),
('CHECK (f_difficulty_level BETWEEN 1 AND 5)'),
('CONSTRAINT uq_training_fields_name'),
('UNIQUE (f_name)'),
(');'),
('GO'),
('CREATE TABLE dbo.scores ('),
('score_id   BIGINT IDENTITY(1'),
('member_id  BIGINT               NOT NULL'),
('sc_points  FLOAT                NOT NULL'),
(NULL),
('CONSTRAINT pk_scores PRIMARY KEY (score_id)'),
('CONSTRAINT ck_scores_points CHECK (sc_points >= 0.0)'),
('CONSTRAINT fk_scores_member'),
('FOREIGN KEY (member_id) REFERENCES dbo.club_members(member_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.sessions ('),
('session_id                    BIGINT IDENTITY(1'),
('field_id                      BIGINT               NOT NULL'),
('s_starts_at                   DATETIME2(0)         NOT NULL'),
('s_duration_minutes            INT                  NOT NULL'),
('s_max_number_of_participants  INT                  NOT NULL'),
(NULL),
('CONSTRAINT pk_sessions PRIMARY KEY (session_id)'),
('CONSTRAINT ck_sessions_duration'),
('CHECK (s_duration_minutes > 0)'),
('CONSTRAINT ck_sessions_max_participants'),
('CHECK (s_max_number_of_participants >= 1)'),
('CONSTRAINT uq_sessions_field_start'),
('UNIQUE (field_id'),
('CONSTRAINT fk_sessions_field'),
('FOREIGN KEY (field_id) REFERENCES dbo.training_fields(field_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.trainers ('),
('trainer_id                   BIGINT IDENTITY(1'),
('member_id                    BIGINT               NULL'),
('t_joined_at                  DATETIME2(0)         NOT NULL'),
('CONSTRAINT df_trainers_joined_at DEFAULT SYSDATETIME()'),
('t_total_amount_of_trainings  INT                  NOT NULL'),
('CONSTRAINT df_trainers_total_trainings DEFAULT 0'),
(NULL),
('CONSTRAINT pk_trainers PRIMARY KEY (trainer_id)'),
('CONSTRAINT ck_trainers_total_trainings'),
('CHECK (t_total_amount_of_trainings >= 0)'),
('CONSTRAINT uq_trainers_member UNIQUE (member_id)'),
('CONSTRAINT fk_trainers_member'),
('FOREIGN KEY (member_id) REFERENCES dbo.club_members(member_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.bookings ('),
('booking_id            BIGINT IDENTITY(1'),
('member_id             BIGINT               NOT NULL'),
('session_id            BIGINT               NULL'),
('preferred_field_id    BIGINT               NULL'),
('reservation_status_id SMALLINT             NOT NULL'),
('requested_at          DATETIME2(0)         NOT NULL'),
('CONSTRAINT df_bookings_requested_at DEFAULT SYSDATETIME()'),
(NULL),
('CONSTRAINT pk_bookings PRIMARY KEY (booking_id)'),
('CONSTRAINT fk_bookings_member'),
('FOREIGN KEY (member_id) REFERENCES dbo.club_members(member_id)'),
('CONSTRAINT fk_bookings_session'),
('FOREIGN KEY (session_id) REFERENCES dbo.sessions(session_id)'),
('CONSTRAINT fk_bookings_preferred_field'),
('FOREIGN KEY (preferred_field_id) REFERENCES dbo.training_fields(field_id)'),
('CONSTRAINT fk_bookings_reservation_status'),
('FOREIGN KEY (reservation_status_id) REFERENCES dbo.reservation_statuses(status_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.payments ('),
('payment_id  BIGINT IDENTITY(1'),
('booking_id  BIGINT               NOT NULL'),
('p_amount    DECIMAL(10'),
('p_date      DATETIME2(0)         NULL'),
('method_id   SMALLINT             NOT NULL'),
('currency_id SMALLINT             NOT NULL'),
('status_id   SMALLINT             NOT NULL'),
(NULL),
('CONSTRAINT pk_payments PRIMARY KEY (payment_id)'),
('CONSTRAINT ck_payments_amount CHECK (p_amount >= 0)'),
('CONSTRAINT fk_payments_booking'),
('FOREIGN KEY (booking_id) REFERENCES dbo.bookings(booking_id) ON DELETE CASCADE'),
('CONSTRAINT fk_payments_currency'),
('FOREIGN KEY (currency_id) REFERENCES dbo.currencies(currency_id)'),
('CONSTRAINT fk_payments_method'),
('FOREIGN KEY (method_id) REFERENCES dbo.payment_methods(method_id)'),
('CONSTRAINT fk_payments_status'),
('FOREIGN KEY (status_id) REFERENCES dbo.payment_statuses(status_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.sessions_trainers ('),
('session_id     BIGINT       NOT NULL'),
('trainer_id     BIGINT       NOT NULL'),
('st_role        NVARCHAR(50) NULL'),
('st_assigned_at DATETIME2(0) NULL'),
(NULL),
('CONSTRAINT pk_sessions_trainers'),
('PRIMARY KEY (session_id'),
('CONSTRAINT fk_sessions_trainers_session'),
('FOREIGN KEY (session_id) REFERENCES dbo.sessions(session_id) ON DELETE CASCADE'),
('CONSTRAINT fk_sessions_trainers_trainer'),
('FOREIGN KEY (trainer_id) REFERENCES dbo.trainers(trainer_id)'),
(');'),
('GO'),
('CREATE TABLE dbo.booking_equipment ('),
('booking_id   BIGINT NOT NULL'),
('bow_id       BIGINT NOT NULL'),
('be_quantity  INT    NOT NULL'),
(NULL),
('CONSTRAINT pk_booking_equipment'),
('PRIMARY KEY (booking_id'),
('CONSTRAINT ck_booking_equipment_quantity'),
('CHECK (be_quantity >= 1)'),
('CONSTRAINT fk_booking_equipment_booking'),
('FOREIGN KEY (booking_id) REFERENCES dbo.bookings(booking_id) ON DELETE CASCADE'),
('CONSTRAINT fk_booking_equipment_bow'),
('FOREIGN KEY (bow_id) REFERENCES dbo.equipment(bow_id)'),
(');');
