CREATE TABLE "mytable" (
  "DECLARE @items dbo.BookingEquipmentItem;" text
);

INSERT INTO "mytable" ("DECLARE @items dbo.BookingEquipmentItem;")
VALUES
('INSERT INTO @items (bow_id'),
('VALUES (1'),
('(3'),
('EXEC dbo.sp_create_booking_with_equipment'),
('@p_member_id = 10'),
('@p_session_id = 4'),
('@items = @items;'),
('GO'),
('CREATE OR ALTER TRIGGER dbo.trg_payments_update_booking_status'),
('ON dbo.payments'),
('AFTER INSERT'),
('AS'),
('BEGIN'),
('SET NOCOUNT ON;'),
(';WITH changed AS ('),
('SELECT booking_id FROM inserted'),
('UNION'),
('SELECT booking_id FROM deleted'),
(')'),
('SELECT DISTINCT booking_id'),
('INTO #changed_bookings'),
('FROM changed'),
('WHERE booking_id IS NOT NULL;'),
('IF NOT EXISTS (SELECT 1 FROM #changed_bookings)'),
('RETURN;'),
('DECLARE'),
('@v_paid_status_id   INT'),
('@v_res_pending_id   INT'),
('@v_res_confirmed_id INT;'),
('SELECT @v_paid_status_id = status_id'),
('FROM dbo.payment_statuses'),
('WHERE name = ''paid'';'),
('SELECT @v_res_pending_id = status_id'),
('FROM dbo.reservation_statuses'),
('WHERE name = ''pending'';'),
('SELECT @v_res_confirmed_id = status_id'),
('FROM dbo.reservation_statuses'),
('WHERE name = ''confirmed'';'),
('IF @v_paid_status_id IS NULL'),
('OR @v_res_pending_id IS NULL'),
('OR @v_res_confirmed_id IS NULL'),
('BEGIN'),
('RAISERROR(''Required payment/reservation statuses not found'''),
('RETURN;'),
('END'),
('UPDATE b'),
('SET reservation_status_id ='),
('CASE'),
('WHEN EXISTS ('),
('SELECT 1'),
('FROM dbo.payments p'),
('WHERE p.booking_id = b.booking_id'),
('AND p.status_id = @v_paid_status_id'),
(')'),
('THEN @v_res_confirmed_id'),
('ELSE @v_res_pending_id'),
('END'),
('FROM dbo.bookings b'),
('JOIN #changed_bookings c'),
('ON c.booking_id = b.booking_id;'),
('END;'),
('GO'),
('SELECT b.booking_id'),
('FROM dbo.bookings b'),
('JOIN dbo.reservation_statuses rs ON rs.status_id = b.reservation_status_id'),
('WHERE b.booking_id = 1;'),
('INSERT INTO payments (booking_id'),
('SELECT'),
('1'),
('100.00'),
('GETDATE()'),
('(SELECT TOP 1 method_id   FROM payment_methods)'),
('(SELECT TOP 1 currency_id FROM currencies)'),
('(SELECT status_id FROM payment_statuses WHERE name = ''paid'');');
