CREATE TABLE "mytable" (
  "CREATE OR ALTER VIEW dbo.v_bow_popularity" text
);

INSERT INTO "mytable" ("CREATE OR ALTER VIEW dbo.v_bow_popularity")
VALUES
('AS'),
('SELECT'),
('e.bow_id'),
('e.b_model'),
('SUM(be.be_quantity) AS total_quantity'),
('FROM dbo.equipment          AS e'),
('JOIN dbo.booking_equipment  AS be'),
('ON be.bow_id = e.bow_id'),
('GROUP BY'),
('e.bow_id'),
('e.b_model;'),
('select * from dbo.v_bow_popularity'),
('CREATE OR ALTER VIEW dbo.v_dictionaries'),
('AS'),
('SELECT'),
('''reservation_status'' AS dict'),
('CAST(rs.status_id AS varchar(10)) AS id'),
('CAST(rs.name      AS varchar(50)) AS name'),
('FROM dbo.reservation_statuses AS rs'),
('UNION ALL'),
('SELECT'),
('''payment_method'' AS dict'),
('CAST(pm.method_id AS varchar(10)) AS id'),
('CAST(pm.name      AS varchar(50)) AS name'),
('FROM dbo.payment_methods AS pm'),
('UNION ALL'),
('SELECT'),
('''payment_status'' AS dict'),
('CAST(ps.status_id AS varchar(10)) AS id'),
('CAST(ps.name      AS varchar(50)) AS name'),
('FROM dbo.payment_statuses AS ps'),
('UNION ALL'),
('SELECT'),
('''currency'' AS dict'),
('CAST(c.currency_id AS varchar(10)) AS id'),
('CAST(c.code        AS varchar(50)) AS name'),
('FROM dbo.currencies AS c;'),
('select * from dbo.v_dictionaries'),
('CREATE OR ALTER VIEW dbo.v_equipment_catalog'),
('AS'),
('SELECT'),
('bow_id'),
('b_model'),
('b_weight'),
('b_length'),
('FROM dbo.equipment;'),
('select * from dbo.v_equipment_catalog'),
('CREATE OR ALTER VIEW dbo.v_field_utilization_monthly'),
('AS'),
('SELECT'),
('tf.field_id'),
('tf.f_name AS field_name'),
('CAST(DATEFROMPARTS('),
('YEAR(s.s_starts_at)'),
('MONTH(s.s_starts_at)'),
('1'),
(') AS date) AS [month]'),
('COUNT(*)                      AS sessions_count'),
('SUM(s.s_duration_minutes)     AS scheduled_minutes'),
('FROM dbo.sessions         AS s'),
('JOIN dbo.training_fields  AS tf'),
('ON tf.field_id = s.field_id'),
('GROUP BY'),
('tf.field_id'),
('tf.f_name'),
('CAST(DATEFROMPARTS('),
('YEAR(s.s_starts_at)'),
('MONTH(s.s_starts_at)'),
('1'),
(') AS date);'),
('select * from dbo.v_field_utilization_monthly'),
('CREATE OR ALTER VIEW dbo.v_member_ids'),
('AS'),
('SELECT member_id'),
('FROM dbo.club_members;'),
('select * from dbo.v_member_ids'),
('CREATE OR ALTER VIEW dbo.v_member_scores'),
('AS'),
('SELECT'),
('cm.member_id'),
('cm.m_name + '' '' + cm.m_surname AS member_name'),
('s.sc_points'),
('FROM dbo.scores        AS s'),
('JOIN dbo.club_members  AS cm'),
('ON cm.member_id = s.member_id;'),
('select * from dbo.v_member_scores'),
('CREATE OR ALTER VIEW dbo.v_sessions_basic'),
('AS'),
('SELECT'),
('s.session_id'),
('tf.f_name              AS field_name'),
('s.s_starts_at'),
('s.s_duration_minutes'),
('s.s_max_number_of_participants'),
('FROM dbo.sessions         AS s'),
('JOIN dbo.training_fields  AS tf'),
('ON tf.field_id = s.field_id;'),
('select * from dbo.v_sessions_basic'),
('CREATE OR ALTER VIEW dbo.v_sessions_overview'),
('AS'),
('WITH load AS ('),
('SELECT'),
('s.session_id'),
('COUNT(b.booking_id) AS current_bookings'),
('FROM dbo.sessions AS s'),
('LEFT JOIN dbo.bookings AS b'),
('ON b.session_id = s.session_id'),
('GROUP BY s.session_id'),
(')'),
('trainer_names AS ('),
('SELECT'),
('s.session_id'),
('COALESCE('),
('cm.m_name + '' '' + cm.m_surname'),
('''Trener #'' + CAST(t.trainer_id AS varchar(10))'),
(') AS trainer_name'),
('FROM dbo.sessions AS s'),
('JOIN dbo.sessions_trainers AS st'),
('ON st.session_id = s.session_id'),
('JOIN dbo.trainers AS t'),
('ON t.trainer_id = st.trainer_id'),
('LEFT JOIN dbo.club_members AS cm'),
('ON cm.member_id = t.member_id'),
(')'),
('trainers AS ('),
('SELECT'),
('tn.session_id'),
('STRING_AGG(tn.trainer_name'),
('FROM ('),
('SELECT DISTINCT session_id'),
('FROM trainer_names'),
(') AS tn'),
('GROUP BY tn.session_id'),
(')'),
('SELECT'),
('s.session_id'),
('s.s_starts_at'),
('s.s_duration_minutes'),
('tf.f_name             AS field_name'),
('tf.f_difficulty_level'),
('tf.f_is_outdoors'),
('s.s_max_number_of_participants'),
('ISNULL(l.current_bookings'),
('CASE'),
('WHEN s.s_max_number_of_participants - ISNULL(l.current_bookings'),
('THEN 0'),
('ELSE s.s_max_number_of_participants - ISNULL(l.current_bookings'),
('END AS free_slots'),
('ISNULL(tr.trainers'),
('FROM dbo.sessions         AS s'),
('JOIN dbo.training_fields  AS tf'),
('ON tf.field_id = s.field_id'),
('LEFT JOIN load     AS l'),
('ON l.session_id = s.session_id'),
('LEFT JOIN trainers AS tr'),
('ON tr.session_id = s.session_id;'),
('select * from dbo.v_sessions_overview'),
('CREATE OR ALTER VIEW dbo.v_trainer_workload_next_30d'),
('AS'),
('SELECT'),
('t.trainer_id'),
('COALESCE('),
('cm.m_name + '' '' + cm.m_surname'),
('''Trener #'' + CAST(t.trainer_id AS varchar(10))'),
(') AS trainer_name'),
('COUNT(s.session_id)                             AS sessions_count'),
('ISNULL(SUM(s.s_duration_minutes)'),
('MIN(s.s_starts_at)                             AS first_session'),
('MAX(s.s_starts_at)                             AS last_session'),
('SUM(CASE WHEN st.st_role = ''lead''      THEN 1 ELSE 0 END) AS lead_sessions'),
('SUM(CASE WHEN st.st_role = ''assistant'' THEN 1 ELSE 0 END) AS assistant_sessions'),
('FROM dbo.trainers AS t'),
('LEFT JOIN dbo.sessions_trainers AS st'),
('ON st.trainer_id = t.trainer_id'),
('LEFT JOIN dbo.sessions AS s'),
('ON s.session_id = st.session_id'),
('AND s.s_starts_at >= GETDATE()'),
('AND s.s_starts_at < DATEADD(DAY'),
('LEFT JOIN dbo.club_members AS cm'),
('ON cm.member_id = t.member_id'),
('GROUP BY'),
('t.trainer_id'),
('COALESCE('),
('cm.m_name + '' '' + cm.m_surname'),
('''Trener #'' + CAST(t.trainer_id AS varchar(10))'),
(');'),
('select * from dbo.v_trainer_workload_next_30d'),
('CREATE OR ALTER VIEW dbo.v_training_fields_overview'),
('AS'),
('SELECT'),
('tf.field_id'),
('tf.f_name            AS field_name'),
('tf.f_difficulty_level'),
('tf.f_capacity'),
('CASE'),
('WHEN tf.f_is_outdoors = 1 THEN ''outdoor'''),
('ELSE ''indoor'''),
('END AS location_type'),
('FROM dbo.training_fields AS tf;'),
('select * from dbo.v_training_fields_overview');
