CREATE TABLE "mytable" (
  "CREATE SCHEMA IF NOT EXISTS archery AUTHORIZATION CURRENT_USER;" text
);

INSERT INTO "mytable" ("CREATE SCHEMA IF NOT EXISTS archery AUTHORIZATION CURRENT_USER;")
VALUES
('SET search_path TO archery'),
('------------------Słowniki-------------------'),
('CREATE TABLE reservation_statuses ('),
('status_id   smallserial PRIMARY KEY'),
('name        text UNIQUE NOT NULL'),
(');'),
('INSERT INTO reservation_statuses(name) VALUES'),
('(''pending'')'),
('CREATE TABLE payment_statuses ('),
('status_id   smallserial PRIMARY KEY'),
('name        text UNIQUE NOT NULL'),
(');'),
('INSERT INTO payment_statuses(name) VALUES'),
('(''pending'')'),
('CREATE TABLE payment_methods ('),
('method_id   smallserial PRIMARY KEY'),
('name        text UNIQUE NOT NULL'),
(');'),
('INSERT INTO payment_methods(name) VALUES'),
('(''card'')'),
('CREATE TABLE currencies ('),
('currency_id smallserial PRIMARY KEY'),
('code        char(3) UNIQUE NOT NULL'),
(');'),
('INSERT INTO currencies(code) VALUES (''PLN'')'),
('------------------Główne tabele-------------------'),
('------------------club_members-------------------'),
('CREATE TABLE club_members ('),
('member_id        bigserial PRIMARY KEY'),
('m_name           text NOT NULL'),
('m_surname        text NOT NULL'),
('m_email          text UNIQUE'),
('m_phone_number   text UNIQUE NOT NULL'),
('m_last_active    timestamptz NOT NULL DEFAULT now()'),
(');'),
('------------------trainers-------------------'),
('CREATE TABLE trainers ('),
('trainer_id                    bigserial PRIMARY KEY'),
('member_id                     bigint UNIQUE REFERENCES club_members(member_id)'),
('t_joined_at                   timestamptz NOT NULL DEFAULT now()'),
('t_total_amount_of_trainings   integer NOT NULL DEFAULT 0 CHECK (t_total_amount_of_trainings >= 0)'),
(');'),
('------------------training_fields-------------------'),
('CREATE TABLE training_fields ('),
('field_id            bigserial PRIMARY KEY'),
('f_difficulty_level  integer NOT NULL CHECK (f_difficulty_level BETWEEN 1 AND 5)'),
('f_is_outdoors       boolean NOT NULL'),
('f_name              text NOT NULL UNIQUE'),
('f_capacity          integer NOT NULL CHECK (f_capacity >= 1)'),
(');'),
('------------------sessions-------------------'),
('CREATE TABLE sessions ('),
('session_id                     bigserial PRIMARY KEY'),
('field_id                       bigint NOT NULL REFERENCES training_fields(field_id)'),
('s_starts_at                    timestamptz NOT NULL'),
('s_duration_minutes             integer NOT NULL CHECK (s_duration_minutes > 0)'),
('s_max_number_of_participants   integer NOT NULL CHECK (s_max_number_of_participants >= 1)'),
('CONSTRAINT uq_sessions_field_start UNIQUE (field_id'),
(');'),
('------------------bookings-------------------'),
('CREATE TABLE bookings ('),
('booking_id           bigserial PRIMARY KEY'),
('member_id            bigint NOT NULL REFERENCES club_members(member_id)'),
('session_id           bigint REFERENCES sessions(session_id)'),
('preferred_field_id   bigint REFERENCES training_fields(field_id)'),
('reservation_status_id smallint NOT NULL REFERENCES reservation_statuses(status_id)'),
('requested_at         timestamptz NOT NULL DEFAULT now()'),
(');'),
('------------------payments-------------------'),
('CREATE TABLE payments ('),
('payment_id     bigserial PRIMARY KEY'),
('booking_id     bigint NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE'),
('p_amount       numeric(10'),
('p_date         timestamptz'),
('method_id      smallint NOT NULL REFERENCES payment_methods(method_id)'),
('currency_id    smallint NOT NULL REFERENCES currencies(currency_id)'),
('status_id      smallint NOT NULL REFERENCES payment_statuses(status_id)'),
(');'),
('------------------equipment-------------------'),
('CREATE TABLE equipment ('),
('bow_id     bigserial PRIMARY KEY'),
('b_model    text NOT NULL'),
('b_weight   text NOT NULL'),
('b_length   text NOT NULL'),
(');'),
('------------------booking_equipment-------------------'),
('CREATE TABLE booking_equipment ('),
('booking_id    bigint  NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE'),
('bow_id        bigint  NOT NULL REFERENCES equipment(bow_id)'),
('be_quantity   integer NOT NULL CHECK (be_quantity >= 1)'),
('PRIMARY KEY (booking_id'),
(');'),
('------------------sessions_trainers-------------------'),
('CREATE TABLE sessions_trainers ('),
('session_id      bigint NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE'),
('trainer_id      bigint NOT NULL REFERENCES trainers(trainer_id)'),
('st_role         text'),
('st_assigned_at  timestamptz'),
('PRIMARY KEY (session_id'),
(');'),
('------------------scores-------------------'),
('CREATE TABLE scores ('),
('score_id     bigserial PRIMARY KEY'),
('session_id   bigint NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE'),
('member_id    bigint NOT NULL REFERENCES club_members(member_id)'),
('sc_points    double precision NOT NULL CHECK (sc_points >= 0)'),
('CONSTRAINT uq_score_member_session UNIQUE (session_id'),
(');');
